# Generated by Django 4.2.6 on 2023-10-25 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcool_level', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('pint_price', models.IntegerField()),
                ('half_price', models.IntegerField()),
                ('ibu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BeerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('origin_country', models.CharField(max_length=50)),
                ('origin_region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DraftFaucet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('co2', models.BooleanField(default=True)),
                ('faucet_flow', models.IntegerField()),
                ('start_up_time', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('pressure', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrel_left', models.IntegerField()),
                ('barrel_price', models.IntegerField()),
                ('working_pressure', models.IntegerField()),
                ('working_temperature', models.IntegerField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.beer')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=50)),
                ('present_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.beer')),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.beertype'),
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.brewery'),
        ),
        migrations.AddField(
            model_name='beer',
            name='draft_faucet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.draftfaucet'),
        ),
        migrations.AddField(
            model_name='beer',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.supplier'),
        ),
    ]
