# Generated by Django 4.2.6 on 2023-10-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='name',
            field=models.CharField(default='bière', max_length=60),
        ),
    ]
